import {
  Sword,
  Shield,
  Zap,
  Heart,
  BowArrow,
  Sparkles,
  WandSparkles,
  ChefHat,
  Axe,
  Navigation,
  Fish,
  Flame,
  Scissors,
  Hammer,
  Pickaxe,
  FlaskConical,
  Activity,
  Hand,
  Skull,
  Sprout,
  CircleSlash2,
  Footprints,
  Home,
} from "lucide-react";

export const iconMap = {
  Attack: Sword,
  Defence: Shield,
  Strength: Zap,
  Hitpoints: Heart,
  Ranged: BowArrow,
  Prayer: Sparkles,
  Magic: WandSparkles,
  Cooking: ChefHat,
  Woodcutting: Axe,
  Fletching: Navigation,
  Fishing: Fish,
  Firemaking: Flame,
  Crafting: Scissors,
  Smithing: Hammer,
  Mining: Pickaxe,
  Herblore: FlaskConical,
  Agility: Activity,
  Thieving: Hand,
  Slayer: Skull,
  Farming: Sprout,
  Runecraft: CircleSlash2,
  Hunter: Footprints,
  Construction: Home,
};
